sanscript/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.views import login, logout
from django.apps import apps

urlpatterns = [
    # Examples:
    # url(r'^$', 'sanscript.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$', login, {'template_name': 'login.html'}),
    url(r'^accounts/logout/$', logout, {'next_page': '/'}),
    url(r'^docs/$', 'sanscript.views.home'),
    url(r'^$', 'sanscript.views.home'),
]

for app in apps.get_app_configs():
    if app.name[:5] == 'apps.':
        urlpatterns += [
            url(r'^{}/'.format(app.label), include('apps.{}.urls'.format(app.label))),
            url(r'^{}-sa/'.format(app.label), include('apps.sa.urls')),
        ]

apps/bc/models.py
from django.db import models
from jsonfield import JSONField


# ==============================================================================


class SwitchConnection(models.Model):
    name = models.CharField(max_length=30, unique=True)
    address = models.CharField(max_length=256, unique=True)
    enabled = models.BooleanField(default=True)
    order = models.IntegerField(null=True, blank=True)

    class Meta:
        ordering = ['order', 'pk']


class CounterOid(models.Model):
    number = models.CharField(max_length=64, unique=True)
    name = models.CharField(max_length=64, unique=True)
    enabled = models.BooleanField(default=True)
    order = models.IntegerField(null=True, blank=True)

    class Meta:
        ordering = ['order', 'pk']

# ==============================================================================

class XTimes(models.Model):
    date = models.DateField()
    values = JSONField()

class Deltas(models.Model):
    date = models.DateField()
    values = JSONField()

class CDicts(models.Model):
    date = models.DateField()
    values = JSONField()

class PDicts(models.Model):
    date = models.DateField()
    values = JSONField()

class SDicts(models.Model):
    date = models.DateField()
    values = JSONField()

class FDicts(models.Model):
    date = models.DateField()
    values = JSONField()

class Integers(models.Model):
    date = models.DateField()
    values = JSONField()

class PortConfig(models.Model):
    switchname = models.CharField(max_length=30)
    portindex = models.IntegerField()
    portname = models.CharField(max_length=60)
    porttype = models.IntegerField()


class Last(models.Model):
    values = JSONField()

apps/en/models.py
from django.db import models

# ==============================================================================

class Connection(models.Model):
    name = models.CharField(max_length=30, unique=True)
    address = models.CharField(max_length=255, unique=True)

class Enclosure(models.Model):
    Location = models.CharField(max_length=64)
    Enclosure_Name = models.CharField(max_length=64)
    Enclosure_SN = models.CharField(max_length=64)
    
class Server(models.Model):
    Enclosure_Name = models.CharField(max_length=64)
    Server_Bay = models.CharField(max_length=64)
    Server_NAME = models.CharField(max_length=64)
    Power_state = models.CharField(max_length=64)
    Server_SN = models.CharField(max_length=64)
    Server_iLO = models.CharField(max_length=64)
    Server_Model = models.CharField(max_length=64)
    RAM_size = models.CharField(max_length=64)
    CPU_count =models.CharField(max_length=64)
    CPU_cores = models.CharField(max_length=64)
    CPU_type = models.CharField(max_length=256)


class Mezzanine(models.Model):
    Server_Bay = models.CharField(max_length=64)
    Mezz_Name = models.CharField(max_length=64)
    Enclosure_Name = models.CharField(max_length=64)
    Ports = models.CharField(max_length=300)
    Server_SN = models.CharField(max_length=64)

#{'Location': 5, 'Enclosure Name': 11, 'Enclosure SN': 10}
#{'Server Bay': 1, 'Server NAME': 17, 'Enclosure Name': 11, 'Power state': 3, 'Server SN': 10, 'Server iLO': 11, 'Server Model': 18}
#{'Server Bay': 1, 'Mezz Name': 55, 'Enclosure Name': 11, 'Ports': 4, 'Server SN': 10}

apps/monitor/models.py
from django.db import models


class BaseItem(models.Model):
    table = models.CharField(max_length=100, unique=True)
    name = models.CharField(max_length=100, unique=True)
    def __str__(self):
        return self.name
    class Meta:
        abstract = True
        ordering = ['id']


class ObjectItem(BaseItem):
    pass


class TriggerItem(BaseItem):
    pass


class Rule(models.Model):
    operators = (
        ('and', 'and'),
        ('or', 'or'),
    )
    name = models.CharField(max_length=100)
    object_item = models.ForeignKey(ObjectItem, blank=True, null=True)
    object_terms_oper = models.CharField(max_length=3, choices=operators, default='and')
    trigger_item = models.ForeignKey(TriggerItem, blank=True, null=True)
    trigger_terms_oper = models.CharField(max_length=3, choices=operators, default='and')
    severity = models.PositiveSmallIntegerField(choices=(
        (0, 'Emergency'),
        (1, 'Alert'),
        (2, 'Critical'),
        (3, 'Error'),
        (4, 'Warning'),
        (5, 'Notice'),
        (6, 'Informational'),
        (7, 'Debug'),
    ), default=6)


class BaseTerm(models.Model):
    field = models.CharField(max_length=100)
    condition = models.CharField(max_length=100)
    value = models.CharField(max_length=100)
    rule = models.ForeignKey(Rule, null=True)
    def __str__(self):
        return self.field
    class Meta:
        abstract = True
        ordering = ['id']

class ObjectTerm(BaseTerm):
    pass

class TriggerTerm(BaseTerm):
    pass


class Action(models.Model):
    method = models.CharField(max_length=100)
    target = models.CharField(max_length=100)
    rule = models.ForeignKey(Rule, null=True)

apps/sa/models.py
from django.db import models


class AppDataLastUpdate(models.Model):
    appname = models.CharField(max_length=16)
    datetime = models.DateTimeField(auto_now_add=True)

apps/monitor/forms.py
from django import forms
from .models import *
from django.apps import apps
from django.forms.models import modelformset_factory


tables = [('', '')]
for app in apps.get_app_configs():
    if app.name.startswith('apps.'):
        for model in app.models:
            app_table = '{} {}'.format(app.label, model)
            tables.append((app_table, app_table))


class ObjectItemForm(forms.ModelForm):
    class Meta:
        model = ObjectItem
        exclude = ()
    table = forms.ChoiceField(choices=tables)


class TriggerItemForm(forms.ModelForm):
    class Meta:
        model = TriggerItem
        exclude = ()


class RuleForm(forms.ModelForm):
    class Meta:
        model = Rule
        exclude = ()
        widgets = {
            'object_terms_oper': forms.RadioSelect(),
            'trigger_terms_oper': forms.RadioSelect(),
        }


class RuleObjectItemForm(forms.Form):
    name = forms.ChoiceField(
        choices = [('', '')] +
        [(o.id, o.name) for o in ObjectItem.objects.all()]
    )

action_methods = [
    ('', '---------'),
    ('email', 'send email'),
    ('log', 'write log'),
]
ActionFormSet = modelformset_factory(
    Action,
    can_delete=True,
    exclude=('rule',),
    widgets={
        'method': forms.Select(choices=action_methods),
    }
)

apps/monitor/views.py
from django.shortcuts import render, redirect
from .forms import *
from .models import *

import os
import json
from django import forms
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.forms.models import modelformset_factory
from .models import *
from .forms import *
from django.apps import apps
from django.db.models import Q
from operator import or_
from functools import reduce
from datetime import datetime

from django.core.mail import send_mail
from django.conf import settings


SEVERITY_NAMES = (
    'Emergency',
    'Alert',
    'Critical',
    'Error',
    'Warning',
    'Notice',
    'Informational',
    'Debug',
)

# Create your views here.
def home(request):
    return render(request, 'home.html')


def san_send_email(to_email, message):
    subject = "SANscript Monitor"
    from_email = settings.DEFAULT_FROM_EMAIL
    try:
        send_mail(subject, message, from_email, [to_email])
        success = 'success'
        message = 'successfully'
    except Exception as e:
        success = 'warning'
        message = e
    return success, message


def san_write_log(filepath, message):
    if not filepath.startswith('/'):
        filepath = os.path.join('apps/monitor/logs', filepath)
    try:
        f = open(filepath, 'a')
        f.write(message)
        f.close()
        success = 'success' 
        message = 'successfully'
    except Exception as e:
        success = 'warning'
        message = e
    return success, message


def perform_actions(actions, message):
    results = []
    for action in actions:
        method = action.method
        target = action.target
        success = 'success'
        if method == 'email':
            success, result_message = san_send_email(target, message)
        elif method == 'log':
            success, result_message = san_write_log(target, message)

        results.append({
            'method': method,
            'target': target,
            'message': result_message,
            'success': success,
        })
    return results

object_conditions = [
    ('', ''),
    ('gt', 'greater than'),
    ('lt', 'less than'),
    ('exact', 'exact'),
    ('iexact', 'iexact'),
    ('contains', 'contains'),
    ('startswith', 'startswith'),
    ('istartswith', 'istartswith'),
    ('endswith', 'endswith'),
    ('iendswith', 'iendswith'),
]

def create_modelformset(termmodel, fields, conditions):
    ModelFormSet = modelformset_factory(
        termmodel,
        can_delete=True,
        exclude=('rule',),
        widgets={
            'field': forms.Select(choices=fields),
            'condition': forms.Select(choices=conditions),
        }
    )
    return ModelFormSet


def get_rel_am_names(am_name):
    model = apps.get_model(*am_name.split())
    rel_am_names = [am_name]
    for field in model._meta.get_fields():
        if field.is_relation and not field.many_to_one:
            rel_am_meta = field.related_model._meta
            rel_am_names.append('{} {}'.format(rel_am_meta.app_label, rel_am_meta.model_name))
    return rel_am_names

def get_fields(appmodelname):
    app_label, model_name = appmodelname.split()
    model = apps.get_model(app_label, model_name)
    fields = [('', '---------'),]
    for field in model._meta.get_fields():
        if not field.is_relation and field.name != 'id':
            fields.append((field.name, field.name))
    return fields


def models_view(request):
    data = {
        'objectitems': ObjectItem.objects.all(),
    }
    return render(request, 'monitor/models.html', data)


def model_register(request):
    form = ObjectItemForm()
    if request.method == 'POST':
        form = ObjectItemForm(request.POST)
        if form.is_valid():
            object_item = form.save()
            trigger_item = TriggerItem(name=object_item.name, table=object_item.table)
            trigger_item.save()
            return HttpResponseRedirect('/monitor/models/')
    else:
        form = ObjectItemForm()
    data = {
        'form': form,
    }
    return render(request, 'monitor/model_form.html', data)


def model_edit(request):
    obj_id = request.GET.get('id')
    object_item = ObjectItem.objects.get(id=int(obj_id))
    trigger_item = TriggerItem.objects.get(name=object_item.name)
    if request.method == 'POST':
        form = ObjectItemForm(request.POST, instance=object_item)
        if form.is_valid():
            object_item = form.save()
            print(trigger_item.name, object_item.name)
            trigger_item.name = object_item.name
            trigger_item.table = object_item.table
            trigger_item.save()
            print(trigger_item.name, object_item.name)

            return HttpResponseRedirect('/monitor/models/')
    else:
        form = ObjectItemForm(instance=object_item)
        data = {
            'form': form,
            'model': object_item,
        }
        return render(request, 'monitor/model_form.html', data)

def model_unregister(request):
    obj_id = request.GET.get('id')
    object_item = ObjectItem.objects.get(id=int(obj_id))
    trigger_item = TriggerItem.objects.get(name=object_item.name)
    object_item.delete()
    trigger_item.delete()
    return HttpResponseRedirect('/monitor/models/')



def rules_view(request):
    data = {
        'rules': Rule.objects.all()
    }
    return render(request, 'monitor/rules.html', data)


def rule_empty(request):
    rule = Rule(name='xxx')
    rule.save()
    rule_id = rule.id
    return redirect('/monitor/rule?id={}'.format(str(rule_id)))


def rule_delete_view(request):
    rule_id = request.GET.get('id')
    rule = Rule.objects.get(id=rule_id)
    rule.delete()
    return HttpResponseRedirect('/monitor/rules/')


# ==============================================================================

def rule_check(rule):

    def filter_by_terms(model_objs, terms, operator):
        filters = {'{}__{}'.format(t.field, t.condition): t.value for t in terms}
        if operator == 'and':
            objs = model_objs.filter(**filters)
        elif operator == 'or':
            objs = model_objs.filter(reduce(or_, [Q(x) for x in filters.items()]))
        else:
            objs = []
        return objs, filters

    data = {}
    objs = None

    if rule.object_item:
        if rule.objectterm_set.count():
            objs, filters = filter_by_terms(
                apps.get_model(*rule.object_item.table.split()).objects,
                rule.objectterm_set.all(),
                rule.object_terms_oper,
            )
        else:
            objs = apps.get_model(*rule.object_item.table.split()).objects.all()
            filters = None

        data.update({
            'object_filter_terms': filters,
            'object_hits': objs.count(),
        })

    if objs and rule.trigger_item and rule.triggerterm_set.count():
        objs, filters = filter_by_terms(
            objs,
            rule.triggerterm_set.all(),
            rule.trigger_terms_oper,
        )
        data.update({
            'trigger_filter_terms': filters,
            'trigger_hits': objs.count(),
        })

    message = ''
    if objs:
        message = '{} - {} - {} - {} matches ({})'.format(
            str(datetime.now())[:19], SEVERITY_NAMES[rule.severity], rule.name, objs.count(), objs
        )
        data.update({
            'check_message': message,
        })
    
 
    if objs and rule.action_set.count():
        actions = perform_actions(rule.action_set.all(), message)
        data.update({
            'actions': actions,
        })

    return data

# ==============================================================================




def rule_view(request):

    rule_id = request.GET.get('id')
    check_flag = request.GET.get('check')
    rule = Rule.objects.get(id=rule_id)

    rule_form = RuleForm(instance=rule, prefix='rule')
    if rule.object_item:
        rel_am_names = get_rel_am_names(rule.object_item.table)
        trigger_items = TriggerItem.objects.filter(table__in=rel_am_names)
        rule_form.fields['trigger_item'].queryset = trigger_items

    action_formset = ActionFormSet(queryset=Action.objects.filter(rule=rule), prefix='action')

    data = {
        'rule_id': rule_id,
        'check_flag': check_flag,
        'rule': rule,
        'rule_form': rule_form,
        'action_formset': action_formset,
    }

    ObjectTermFormSet = None
    if rule.object_item:
        fields = get_fields(rule.object_item.table)
        ObjectTermFormSet = create_modelformset(ObjectTerm, fields, object_conditions)
    TriggerTermFormSet = None
    if rule.trigger_item:
        fields = get_fields(rule.trigger_item.table)
        TriggerTermFormSet = create_modelformset(TriggerTerm, fields, object_conditions)

    formset1 = None
    formset2 = None

    if not request.POST:
        if rule.object_item:
            formset1 = ObjectTermFormSet(queryset=ObjectTerm.objects.filter(rule=rule), prefix='object')
        if rule.trigger_item:
            formset2 = TriggerTermFormSet(queryset=TriggerTerm.objects.filter(rule=rule), prefix='trigger')
        data.update({
            'formset1': formset1,
            'formset2': formset2,
        })

        if check_flag:
            data.update(rule_check(rule))

        return render(request, 'monitor/rule_form.html', data)


    if request.POST and request.is_ajax():

        item_id = request.POST.get('object_id')
        if item_id is not None:
            try:
                item = ObjectItem.objects.get(id=int(item_id))
            except:
                item = None
            rule.objectterm_set.all().delete()
            rule.object_item = item

            if not item:
                rule.trigger_item = None
                rule.triggerterm_set.all().delete()
            if item:
                rel_am_names = get_rel_am_names(rule.object_item.table)
                if len(rel_am_names) == 1:

templates/monitor/formset.html
{{ formset.non_form_errors.as_ul }}
{{ formset.management_form }}
<table style="width:100%">
  {% for form in formset.forms %}
    {% if forloop.first %}
      <thead><tr>
        {% for field in form.visible_fields %}
          <th>{% if field.label == 'Delete' %}X{% else %}{{ field.label }}{% endif %}</th>
        {% endfor %}
      </tr></thead>
    {% endif %}
    <tr class="{% cycle row1,row2 %}">
    {% for field in form.visible_fields %}
      <td>
      {# Include the hidden fields in the form #}
      {% if forloop.first %}
        {% for hidden in form.hidden_fields %}
        {{ hidden }}
        {% endfor %}
      {% endif %}
        {{ field.errors.as_ul }}
        {{ field }}
      </td>
    {% endfor %}
    </tr>
  {% endfor %}
</table>

templates/monitor/model_form.html
{% extends 'base.html' %}
{% block content %}

<div class="row">
  <div class="columns">
    <form method="post" action="">{% csrf_token %}
      {{ form.as_p }}
      <input type="submit" class="button small" value="Save">
      {% if model %}
      <a href="/monitor/model_unregister?id={{ model.id }}" class="button small alert right">Unregister</a>
      {% endif %}
    </form>
  </div>
</div>

{% endblock %}

templates/monitor/models.html
{% extends 'base.html' %}
{% block content %}

<div class="row">
  <div class="columns">
    <a href="/monitor/model_register/" class="button small">Register model</a>
    {% for obj in objectitems %}
        <p><a href="/monitor/model_edit?id={{ obj.id }}">{{ obj.name }} = {{ obj.table }}</a></p>
    {% endfor %}
  </div>
</div>

{% endblock %}

templates/monitor/rule_form.html
{% extends 'base.html' %}
{% block content %}


    <style>
      body, input, select {font-size: 85%}
      table tr:nth-of-type(even) {
        background-color: transparent !important;
      }
      tr td{padding: 2px; vertical-align:bottom; text-align:center}
      td select,
      td input[type='radio'],
      td input[type='text'],
      td input[type='number'] {margin-bottom:0; font-size:100%; height:2rem;}

      td input[type='checkbox'] {margin-bottom:0; font-size:100%; height:1.2rem; margin:0 auto;}

      ul {margin-bottom:0}

      ul li { display: inline; }
      ul li { display: inline-block; }
      #id_rule-name {margin-bottom:0 }
    </style>



<form method="post" action="">{% csrf_token %}

<div class="row fullWidth">
  <div class="columns">
    {{ rule_form.non_form_errors.as_ul }}
    {{ rule_form.management_form }}
    {{ rule_form.id }}
    {{ rule_form.name }}
  </div>
</div>

<hr>

<div class="row fullWidth">
  <div class="large-4 medium-6 columns">
    <div class="callout">
    Objects
    <hr>
    {{ rule_form.object_item }}
    {% with formset1 as formset %}
      {% include 'monitor/formset.html' %}
    {% endwith %}
    <div class="callout">
      {{ rule_form.object_terms_oper }}
    </div>
    </div>
  </div>
  <div class="large-4 medium-6 columns">
    <div class="callout">
    Triggers
    <hr>
    {{ rule_form.trigger_item }}
    {% with formset2 as formset %}
      {% include 'monitor/formset.html' %}
    {% endwith %}
    {{ rule_form.trigger_terms_oper }}
    </div>
  </div>
  <div class="large-4 medium-6 columns">
    <div class="callout">
    Actions
    <hr>
    {{ rule_form.severity }}
    {% with action_formset as formset %}
      {% include 'monitor/formset.html' %}
    {% endwith %}
    </div>
  </div>
</div>

<hr>

<div class="row fullWidth noBottom">
  <div class="columns">
    <input type="submit" class="button small noBottom" value="Save"> 
    <a href="/monitor/rule?id={{ rule.id }}&check=true#x" id="check" class="button small noBottom">Check</a>
    <a href="delete" class="button small noBottom alert right">Delete</a>
  </div>
</div>


</form>

{% if check_flag %}

<hr>
<a name="x"></a>
<div class="row fullWidth">
  <div class="large-4 medium-6 columns">
    <div class="callout">
      Objects
      <hr>

      <div>MODEL: {{ rule.object_item.table }}; FILTER: {{ object_filter_terms }}; OPERATOR: {{ rule.object_terms_oper }}</div>
      <br>
      <div class="callout alert-box {% if object_hits %}success{% else %}secondary{% endif %}">MATCHES: {{ object_hits }}</div>



    </div>
  </div>

  <div class="large-4 medium-6 columns">
    <div class="callout">
      Triggers
      <hr>
      {% if trigger_filter_terms %}
      <div>MODEL: {{ rule.trigger_item.table }}; FILTER: {{ trigger_filter_terms }}; OPERATOR: {{ rule.trigger_terms_oper }}</div>
      <br>
      <div class="callout alert-box {% if trigger_hits %}success{% else %}secondary{% endif %}">MATCHES: {{ trigger_hits }}</div>
      {% endif %}

      {% if not object_hits  %}
      <div class="callout alert-box warning">No object matches (&larr;)</div>
      {% endif %}

      {% if not rule.triggerterm_set.count %}
      <div class="callout alert-box warning">No trigger terms (&uarr;)</div>
      {% endif %}

    </div>
  </div>

  <div class="large-4 medium-6 columns">
    <div class="callout">
      Actions
      <hr>

      {% if check_message  %}
      <div >{{ check_message }}</div>
      <br>
      {% endif %}

      {% if not trigger_hits  %}
      <div class="callout alert-box warning">No trigger matches (&larr;)</div>
      {% endif %}

      {% if not rule.action_set.count %}
      <div class="callout alert-box warning">No actions (&uarr;)</div>
      {% endif %}

      {% for action in actions %}
        <div class="callout alert-box {{ action.success }}">{{ action.method }} {{ action.target }} - {{ action.message }}</div>
      {% endfor %}
    </div>
  </div>

</div>

{% endif %}

<br>

{% csrf_token %}
{% endblock %}


{% block script %}
<script>
$('select[name="rule-object_item"]').each(function() {
    //Store old value
    $(this).data('lastValue', $(this).val());
});
$('select[name="rule-object_item"]').on('change', function(e) {
    var lastRole = $(this).data('lastValue');
    if (confirm("All terms will be removed")) {
    $.ajax({
        type: "POST",
        url: "/monitor/rule?id={{ rule_id }}",
        data: {
            csrfmiddlewaretoken: document.getElementsByName('csrfmiddlewaretoken')[0].value,
            object_id: this.value,
        },
        success: function(data) {
            window.location.replace("/monitor/rule?id={{ rule_id }}");
        },
        error: function(xhr, textStatus, errorThrown) {
            alert("Error: "+errorThrown+xhr.status+xhr.responseText);
        }
    });
    }
    else {
        $(this).val(lastRole);
    };
});
$('select[name="rule-trigger_item"]').each(function() {
    //Store old value
    $(this).data('lastValue', $(this).val());
});
$('select[name="rule-trigger_item"]').on('change', function(e) {
    var lastRole = $(this).data('lastValue');
    if (confirm("All terms will be removed")) {
    $.ajax({
        type: "POST",
        url: "/monitor/rule?id={{ rule_id }}",
        data: {
            csrfmiddlewaretoken: document.getElementsByName('csrfmiddlewaretoken')[0].value,
            trigger_id: this.value,
        },
        success: function(data) {
            window.location.replace("/monitor/rule?id={{ rule_id }}");
        },
        error: function(xhr, textStatus, errorThrown) {
            alert("Error: "+errorThrown+xhr.status+xhr.responseText);
        }
    });
    }
    else {
        $(this).val(lastRole);
    };
});

</script>

{% endblock %}

templates/monitor/rules.html
{% extends 'base.html' %}
{% block content %}


    <style>
      body, input, select {font-size: 85%}
      table tr:nth-of-type(even) {
        background-color: transparent !important;
      }
      tr td {padding: 3px}
      td select,
      td input[type='radio'],
      td input[type='text'],
      td input[type='number'] {margin-bottom:0; font-size:100%; height:2rem;}

      .s0 {background:red;} /* Emergency */
      .s1 {background:red;} /* Alert */
      .s2 {background:orange;} /* Critical */
      .s3 {background:orange;} /* Error */
      .s4 {background:yellow;} /* Warning */
      .s5 {background:blue;} /* Notice */
      .s6 {background:green;} /* Informational */
      .s7 {background:green;} /* Debug */
    </style>

<div class="row">
  <div class="columns">
    <a href="/monitor/rule_empty/" class="button small">Create rule</a>

{% for rule in rules %}
  <p>
      <a href="/{{ app_label }}/rule?id={{ rule.id }}">{% if rule.name %}{{ rule.name }}{% else %}{{ rule.id }}{% endif %}</a>
  </p>
{% endfor %}
  </div>
</div>

{% endblock %}